# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Diary App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Diary App

pod 'Alamofire'
pod 'SwiftyJSON'
pod "KRProgressHUD"
pod 'AlamofireObjectMapper'

  target 'Diary AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Diary AppUITests' do
    # Pods for testing
  end

end
